name: 'Run Orca Python Jep Exampletest Py37'
description: 'Run Orca Python Jep Exampletest Py37'
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.10'

    - name: Install dependencies
      shell: bash
      run: |
        apt-get update
        apt-get install wget
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools==58.0.4

    - name: Setup env
      shell: bash
      run: |
        wget -r -np -nH -N ${FTP_URL}/pkgs/* -P ~/.conda/
        cp -n -r ~/.conda/pkgs/*.tar.bz2 /opt/conda/pkgs
        cp -n  ~/.conda/pkgs/cache/* /opt/conda/pkgs/cache
        
        if conda info --env | grep "py37"; then
            source activate py37
        else
            conda create -n py37 -y python==3.7.10 setuptools==58.0.4
            conda info --env
            source activate py37
        fi
        
        pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-friesian bigdl-friesian-spark3
        pip uninstall -r python/orca/dev/example/requirements-jep.txt -y
        pip install -i https://pypi.org/simple --pre --upgrade bigdl-orca
        #pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r python/orca/dev/example/requirements-jep.txt
        export NO_PROXY=172.168.2.182
        pip install -i http://172.168.2.182/simple --trusted-host 172.168.2.182 -r python/orca/dev/example/requirements-jep.txt
        pip uninstall -y opencv-python-headless
        pip install opencv-python-headless
        
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
